sudo: false
language: node_js
before_install:
 - gem install sass
node_js:
- iojs
cache:
  directories:
  - node_modules
script: npm test
after_success: |
  if ([ ! -z "$DEPLOY_TOKEN" ] &&
      [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ] &&
      [ -z "$TRAVIS_TAG" ] &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    echo "Deploying";
    git config --global user.email "$DEPLOY_EMAIL";
    git config --global user.name "$DEPLOY_NAME";
    git remote rm origin;
    git remote add origin "https://$DEPLOY_USER:$DEPLOY_TOKEN@github.com/$TRAVIS_REPO_SLUG.git";
    npm run-script deploy;
    echo "Deployed";
  else
    echo "Skipped deploy"
  fi
env:
  global:
  - DEPLOY_BRANCH="live"
  - DEPLOY_NAME="necccc"
  - DEPLOY_EMAIL="nec@shell8.net"
  - secure: ovqXKyl1VIaBJgftdh2mfgeOOV/Eq7eLXEtaAqafyhFF+LsI+oKWnjeyVTGDtmLRoGCMl0EzqOfclbbMEgg7rzKjiymGGvUfh2kMHQAEKg8rupFFtk/36S4AJZ+AADv+G7KRrW6VWkpwNasmUmKqVcCUYeuz2pZkeeIMtRCZcmSLnTBa0mRJMdOPTsFCGD0XYqUEvyr5ehWKu0izQzjS0vz3eqhj5LabZJ5TBGzOKUl0xwpJSllFKBMCeSrIKqFwxbsirML0bnEOT6pMDbRqZzkdAnWfIiOrokaCHkkY1Z/5iOHgx0F0Z1Q1ds0Qi1yWfVEDJnTauRvA04tdwvy7c5zKP7gXd6ZEJKeLCKaHO5Xmce72dOSebaCRmFbIrCyv+IwA/WhU54RoLC+jUyx+FGPJB3isxAfCI7UYgJGuAv8dr9ghK4Eup6BFNFb/RnzPakHX6PsHVwHcicMphuIzFq4IhaP2yy4RVf+xWioNhjivvo8s136aQe4sZBWMpURvIfY3zAKBOfPv510xXicsYq3HK8vYtHzRu1mWAGWOrURw0K8JuXmiN7KRqkyUuwse7IY7hgnXpA5d0bIwhAAmKWzhAJDGXm+bXqJXJSm3rGg6JXZ5Rw8JzPYFlWy+fMNXX2loc1a8PKNu907S1QoCpS9xIl4/iA8gHc+vviqAEo8=
  - secure: qbyW7xF3PQERXttv//ggc/U2IySPoUitzDJE9LPiZq0GsCs5h5hcKAGipHrCtAxV/aKwyGnLy0gi7c4LkC1NAGGrevh91wcDp1GRURUztQ9U0LmE2hw5GxMm6qwcYOegpkapQq/xsPPDUSppbE68TpSjZJCZKgj9utdann4mMmJh+ALdtOKrEf+ZPKsvwd8KjoXHXrQvwO+Jo4fnio5xPAnp0Crg6Q1eNKMggsyi+w/jPdQeWIqrS2qee9KwpPjLeZWg5macD08KenZkzTTUxWgjhLVx3neT6zE1jwFo4UUN9IPU7LzaxOQ7s94HPyjAx7BdEMs/kTMQOn+l8wpyhM0PZATy2e4ergT5DBrA6ax4DskIR2GRUzNp9hSl6ejYtAreHCjIwBgyd4TeR5402393MIXUIIN/VtWErfdYLGbSdWy386LZLt8KueHgCkqAzVt+yDjfwv9AY8tQuG0VwtrWxNwiI80P6Xw5fKlGwLMX0gKukaSmUzlRoMxeNiY3ElDaHlpZL5kTYAnGUbwpmD7qM1wZwSyhWWwKATXisgCa9FGEiEs/E+iTXFILYfqfYxYCSea8JA9wXwk1rXyfayA87qQunNZ41rsEISgTWhFtpazgSxEhxCjPtXTlI48gzmeuOg7lMhv5nXWyWBd+KZzHxozHU+4pPKeh6QKjYsw=
